-- AlterTable
ALTER TABLE `media` ADD COLUMN `created` DATETIME(3) NULL,
    ADD COLUMN `lat` DECIMAL(65, 30) NULL,
    ADD COLUMN `long` DECIMAL(65, 30) NULL,
    ADD COLUMN `tripId` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `session` MODIFY `secret` LONGBLOB NOT NULL;

-- AddForeignKey
ALTER TABLE `Media` ADD CONSTRAINT `Media_tripId_fkey` FOREIGN KEY (`tripId`) REFERENCES `Trip`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
